services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  root-config:
    build: .
    ports: ["9000:9000"]

  angular-app:
    build: ./angular-app
    ports: ["4201:80"]

  dashboard:
    build: ./dashboard
    ports: ["4200:80"]

  react-app:
    build: ./react-app
    ports: ["8080:80"]

  backend:
    build: ./python-backend
    env_file: ./python-backend/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8000:8000"]

volumes:
  postgres-data: