
services:
  root-config:
    build: .
    ports:
      - "9000:9000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  dashboard:
    build: ./dashboard
    ports:
      - "8080:80"
  react-app:
    build: ./react-app
    ports:
      - "8081:80"
  angular-app:
    build: ./angular-app
    ports:
      - "8082:80"
  python-backend:
    build: ./python-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  db_data:
